server:
  port: 8081
  servlet:
    context-path: /payments-app

integration:
  clients:
    products-client:
      url: "http://localhost:8080/products-app"
      connect-timeout: 3s
      read-timeout: 5s
      get-products-url: "/v1/api/products/all/user/"
      buy-product-url: "/v1/api/products/execute"